image: node:20

stages:          
  - build
  - test
  - deploy

cache:
  paths:
    - frontend/node_modules/
    - backend/node_modules/

before_script:
  - cd $CI_PROJECT_DIR

#build_frontend:
#  stage: build
#  script:
#    - cd frontend
#    - npm install
#    - npm run build
#  artifacts:
#    paths:
#      - frontend/build/

build_backend:
  stage: build
  script:
    - cd backend
    - npm install
  artifacts:
    paths:
      - backend/

#test_frontend:
#  stage: test
#  script:
#    - cd frontend
#    - npm install
#    - npm test

test_backend:
  stage: test
  script:
    - cd backend
    - npm install
    - npm test

#deploy_frontend:
#  stage: deploy
#  script:
#    - cd frontend
#    - npm run deploy
#  environment:
#    name: production
#  only:
#    - feature/login-P3-6
#
#deploy_backend:
#  stage: deploy
#  script:
#    - cd backend
#    - npm run deploy
#  environment:
#    name: production
#  only:
#    - feature/login-P3-6
